[40055c]
addr = 4195676
comment = "***\nthis is my fat function comment\nyeah check it out\nyup.\n\n***\n\n0x40055c: ***\nthis is my fat function comment\nyeah check it out\nyup.\n\n***\n0x40056d: comment\n0x400573: this is a loop\n0x400592: this is an array I think\n0x4005b4: this is just the ret"
