[-7c]
func_addr = 4195902
name = "real_len"
stack_offset = -124
stack_offset_type = 3
size = 4
type = "unsigned int (32 bits)"

[-10]
func_addr = 4195902
name = "v1"
stack_offset = -16
stack_offset_type = 3
size = 8
type = "BOT"
