[4005b6]
addr = 4195766
comment = "this is my decent\nfunc2 comment\nit has an asm comment\n\n0x4005dc: some asm comment\n\n0x4005b6: this is my decent\nfunc2 comment\nit has an asm comment\n\n0x4005dc: some asm comment"
