[-cc]
func_addr = 4195766
name = "fake_len"
stack_offset = -204
stack_offset_type = 3
size = 4
type = "unsigned int (32 bits)"

[-10]
func_addr = 4195766
name = "v1"
stack_offset = -16
stack_offset_type = 3
size = 8
type = "BOT"
