[40055c]
addr = 4195676
name = "not_an_overflow"
track = true

[4005b6]
addr = 4195766
name = "fo_sho_overflow"
track = true

[40063e]
addr = 4195902
name = "renamed_func"
track = true

[40068f]
addr = 4195983
name = "main"
track = true
