[1030]
addr = 4144
comment = "\n\n0x1039: Comment by redgate.\n\n0x1039: Comment by redgate. More comments sdjkflsldf ."

[11a0]
addr = 4512
comment = "\n\n0x11a9: argc"

[11a9]
addr = 4521
comment = "argc"

[20bc]
addr = 8380
comment = "***\nThis function takes in some\nxxx\n\n***\n\n0x2135: this is a format string"

[2135]
addr = 8501
comment = "this is a format string"
ng"
