[1030]
addr = 4144
comment = "\n\n0x1039: Comment by redgate.\n\n0x1039: Comment by redgate. More comments sdjkflsldf .\n\n0x1030: \n\n0x1039: Comment by redgate.\n\n0x1039: Comment by redgate. More comments sdjkflsldf ."

[20bc]
addr = 8380
comment = "***\nThis function takes in some\nuser input and then parses it passing\nit to the next functions. Yup.\n\n***\n\n0x2135: this is a format string"

[2135]
addr = 8501
comment = "this is a format string"
