[1090]
addr = 4240
name = "mahaloz_func"

[201a]
addr = 8218
name = "cool_lookin_function"

[20bc]
addr = 8380
name = "myfunction2"

[1030]
addr = 4144
name = "redgate_func"

[1eac]
addr = 7852
name = "hello2"

[2019]
addr = 8217
name = "yoyo2"

[1c1b]
addr = 7195
name = "new_func_name"

[22b0]
addr = 8880
name = "fini"
