[20bc]
addr = 8380
comment = "***\nThis function takes in some\nuser input and then parses it passing\nit to the next functions. Yup.\n\n***\n\n0x2135: this is a format string\n\n0x20bc: ***\nThis function takes in some\nuser input and then parses it passing\nit to the next functions. Yup.\n\n***\n\n0x2135: this is a format string"
