[40055c]
addr = 4195676
comment = "this is my large\nfunc1 function\ncomment"

[4005b6]
addr = 4195766
comment = "this is my decent\nfunc2 comment\nit has an asm comment\n\n0x4005dc: some asm comment"

[4005dc]
addr = 4195804
comment = "some asm comment"
