[-2c]
func_addr = 4195676
name = "len"
stack_offset = -44
stack_offset_type = 3
size = 4
type = "unsigned int (32 bits)"

[-10]
func_addr = 4195676
name = "v1"
stack_offset = -16
stack_offset_type = 3
size = 8
type = "BOT"
