[-cc]
func_addr = 4195766
name = "var_C4"
stack_offset = -204
stack_offset_type = 1
size = 4
type = "unsigned int"

[-c8]
func_addr = 4195766
name = "var_C0"
stack_offset = -200
stack_offset_type = 1
size = 1
type = "unsigned char"

[-10]
func_addr = 4195766
name = "canary"
stack_offset = -16
stack_offset_type = 1
size = 8
type = "unsigned long long"
