[-28]
func_addr = 4195676
name = "some_var"
stack_offset = -40
stack_offset_type = 1
size = 24
type = "unsigned char"

[-10]
func_addr = 4195676
name = "canary"
stack_offset = -16
stack_offset_type = 1
size = 8
type = "unsigned long long"
